server:
  port: 8083

spring:
  application:
    name: cart-service
  jpa:
    hibernate:
      ddlAuto: update
    databasePlatform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3308/cart_service
    username: root
    password:

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
