spring:
  application:
    name: eureka-sv
  cloud:
    eureka:
      client:
        register-with-eureka: false
        fetch-registry: false
      instance:
        hostname: localhost
        lease-renewal-interval-in-seconds: 0
server:
  port: 8761
